[package]
name = "x86_64"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
log = "0.4"
x86 = "0.47"
multiboot2 = "0.13"
uart_16550 = "0.2"
spin = "0.9"

[dependencies.kernel]
path = "../../kernel"
